/*
 * test_density_64.c - Parity test for triplane sample + NeRF MLP (Phase 9).
 *
 * Reproduces TripoSR's renderer.query_triplane on a uniform 64^3 grid in
 * world space [-radius, +radius]^3 and compares against the golden density
 * + color volumes.
 *
 * Pipeline:
 *   for each chunk of N_chunk points:
 *     1. triplane_sample: positions [N, 3] -> features [N, 120]
 *     2. nerf_mlp:         features [N, 120] -> density [N], color [N, 3]
 *
 * Inputs (regenerated by tools/extract_golden.py):
 *   triposr_env/model.safetensors
 *   tests/golden/triposr/triplane.bin   [1, 3, 40, 64, 64]   post-upsample
 *   tests/golden/triposr/density.bin    [64, 64, 64]         golden density (post-exp)
 *   tests/golden/triposr/color.bin      [64, 64, 64, 3]      golden color (post-sigmoid)
 *
 * Tolerance: density values range 0..5000+, so we use the deep-network
 * (atol=4e-3, rtol=1e-4) pair from LRMengine.md section 10.2.
 *
 * Build: make test-density
 * Run:   ./test_density_64
 */

#include "iris.h"
#include "iris_safetensors.h"
#include "lrm/lrm_nerf_mlp.h"
#include "lrm/lrm_triplane_sample.h"

#include <fcntl.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

static const char *kModelPath    = "triposr_env/model.safetensors";
static const char *kTriplanePath = "tests/golden/triposr/triplane.bin";
static const char *kDensityPath  = "tests/golden/triposr/density.bin";
static const char *kColorPath    = "tests/golden/triposr/color.bin";

#define ATOL_DENSITY 4.0e-3f
#define RTOL_DENSITY 1.0e-4f
#define ATOL_COLOR   1.0e-4f
#define RTOL_COLOR   1.0e-4f

#define GRID_RES   64
#define CHUNK_SIZE 8192

static const float *mmap_f32(const char *path, size_t *out_bytes) {
    int fd = open(path, O_RDONLY);
    if (fd < 0) { perror(path); return NULL; }
    struct stat st;
    if (fstat(fd, &st) != 0) { perror(path); close(fd); return NULL; }
    void *p = mmap(NULL, st.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
    close(fd);
    if (p == MAP_FAILED) { perror(path); return NULL; }
    *out_bytes = (size_t)st.st_size;
    return (const float *)p;
}

typedef struct {
    size_t failures;
    double max_abs_err;
    double max_rel_err;
    double sum_abs;
    size_t worst_abs;
    size_t worst_rel;
} compare_stats_t;

static void compare_into(const float *expected, const float *got, size_t n,
                         float atol, float rtol, compare_stats_t *st) {
    for (size_t i = 0; i < n; i++) {
        float e = expected[i];
        float diff = fabsf(e - got[i]);
        st->sum_abs += diff;
        if (diff > st->max_abs_err) { st->max_abs_err = diff; st->worst_abs = i; }
        double rel = diff / (1e-30 + fabsf(e));
        if (rel > st->max_rel_err) { st->max_rel_err = rel; st->worst_rel = i; }
        float tol = atol + rtol * fabsf(e);
        if (!(diff <= tol)) {
            if (st->failures < 8) {
                fprintf(stderr,
                        "  idx=%zu  expected=% .8e  got=% .8e  |err|=%.3e  tol=%.3e\n",
                        i, (double)e, (double)got[i],
                        (double)diff, (double)tol);
            }
            st->failures++;
        }
    }
}

static int report(const char *name, const float *expected, size_t n,
                  float atol, float rtol, const compare_stats_t *st) {
    fprintf(stderr,
            "  %s: %zu elements\n"
            "    max |err|=%.3e at idx=%zu (expected=% .3e)\n"
            "    max rel =%.3e at idx=%zu (expected=% .3e)\n"
            "    mean |err|=%.3e   atol=%.0e rtol=%.0e\n",
            name, n,
            st->max_abs_err, st->worst_abs, (double)expected[st->worst_abs],
            st->max_rel_err, st->worst_rel, (double)expected[st->worst_rel],
            st->sum_abs / (double)n, (double)atol, (double)rtol);
    return (int)st->failures;
}

int main(void) {
    safetensors_file_t *sf = safetensors_open(kModelPath);
    if (!sf) {
        fprintf(stderr, "FAIL: cannot open %s\n", kModelPath);
        return 1;
    }

    lrm_nerf_mlp mlp;
    if (lrm_nerf_mlp_init(&mlp, sf) != 0) {
        fprintf(stderr, "FAIL: nerf_mlp init: %s\n", iris_get_error());
        safetensors_close(sf);
        return 1;
    }
    fprintf(stderr, "loaded NeRF MLP: in=%d hidden=%d out=%d layers=%d "
                    "density_bias=%.2f\n",
            mlp.in_channels, mlp.hidden_dim, mlp.out_channels,
            mlp.num_layers, mlp.density_bias);

    lrm_triplane_sample_cfg ts_cfg = { 3, 40, 64, 0.87f };

    /* Load triplane (input) and goldens. */
    size_t bytes;
    const float *triplane = mmap_f32(kTriplanePath, &bytes);
    if (!triplane) goto fail;
    const size_t expected_triplane =
        (size_t)ts_cfg.planes * ts_cfg.channels
        * ts_cfg.size * ts_cfg.size * sizeof(float);
    if (bytes != expected_triplane) {
        fprintf(stderr, "FAIL: triplane.bin has %zu bytes, expected %zu\n",
                bytes, expected_triplane);
        goto fail;
    }

    const float *gold_density = mmap_f32(kDensityPath, &bytes);
    if (!gold_density) goto fail;
    const size_t N = (size_t)GRID_RES * GRID_RES * GRID_RES;
    if (bytes != N * sizeof(float)) {
        fprintf(stderr, "FAIL: density.bin %zu bytes, expected %zu\n",
                bytes, N * sizeof(float));
        goto fail;
    }
    const float *gold_color = mmap_f32(kColorPath, &bytes);
    if (!gold_color) goto fail;
    if (bytes != N * 3 * sizeof(float)) {
        fprintf(stderr, "FAIL: color.bin %zu bytes, expected %zu\n",
                bytes, N * 3 * sizeof(float));
        goto fail;
    }

    /* Output buffers. */
    float *got_density = (float *)malloc(N * sizeof(float));
    float *got_color   = (float *)malloc(N * 3 * sizeof(float));
    if (!got_density || !got_color) {
        fprintf(stderr, "FAIL: oom outputs\n");
        free(got_density); free(got_color); goto fail;
    }

    /* Per-chunk scratch. */
    float *positions = (float *)malloc((size_t)CHUNK_SIZE * 3 * sizeof(float));
    float *features  = (float *)malloc((size_t)CHUNK_SIZE * 120 * sizeof(float));
    size_t ts_ws = lrm_triplane_sample_workspace_bytes(&ts_cfg, CHUNK_SIZE);
    size_t nm_ws = lrm_nerf_mlp_workspace_bytes(&mlp, CHUNK_SIZE);
    float *ts_work = (float *)malloc(ts_ws);
    float *nm_work = (float *)malloc(nm_ws);
    if (!positions || !features || !ts_work || !nm_work) {
        fprintf(stderr, "FAIL: oom scratch\n");
        free(positions); free(features); free(ts_work); free(nm_work);
        free(got_density); free(got_color); goto fail;
    }
    fprintf(stderr,
            "chunk=%d, per-chunk: ts_work=%.2f KB, nm_work=%.2f KB, "
            "positions=%.2f KB, features=%.2f KB\n",
            CHUNK_SIZE,
            (double)ts_ws / 1024.0, (double)nm_ws / 1024.0,
            (double)(CHUNK_SIZE * 3 * sizeof(float)) / 1024.0,
            (double)(CHUNK_SIZE * 120 * sizeof(float)) / 1024.0);

    /* Build the linspace lookup. */
    const float r = ts_cfg.radius;
    float lin[GRID_RES];
    for (int i = 0; i < GRID_RES; i++) {
        /* torch.linspace(-r, +r, n=64) inclusive */
        lin[i] = -r + (2.0f * r) * (float)i / (float)(GRID_RES - 1);
    }

    fprintf(stderr, "running %zu queries in chunks of %d ...\n",
            N, CHUNK_SIZE);
    for (size_t off = 0; off < N; off += CHUNK_SIZE) {
        int n_this = (off + CHUNK_SIZE <= N)
                   ? CHUNK_SIZE : (int)(N - off);

        /* Fill positions for this chunk. Flat index p = i*n^2 + j*n + k,
         * with position (lin[i], lin[j], lin[k]) matching meshgrid('ij'). */
        for (int q = 0; q < n_this; q++) {
            size_t p = off + (size_t)q;
            size_t i = p / (GRID_RES * GRID_RES);
            size_t j = (p / GRID_RES) % GRID_RES;
            size_t k = p % GRID_RES;
            float *pos = positions + (size_t)q * 3;
            pos[0] = lin[i];
            pos[1] = lin[j];
            pos[2] = lin[k];
        }

        if (lrm_triplane_sample_forward(&ts_cfg, triplane, positions,
                                        n_this, features, ts_work) != 0) {
            fprintf(stderr, "FAIL: triplane_sample: %s\n", iris_get_error());
            goto fail2;
        }
        if (lrm_nerf_mlp_forward(&mlp, features, n_this,
                                 got_density + off,
                                 got_color + off * 3,
                                 nm_work) != 0) {
            fprintf(stderr, "FAIL: nerf_mlp: %s\n", iris_get_error());
            goto fail2;
        }
    }

    /* Compare both volumes. */
    compare_stats_t s_d = {0}; s_d.max_abs_err = 0;
    compare_stats_t s_c = {0}; s_c.max_abs_err = 0;
    fprintf(stderr, "comparing density (atol=%.0e rtol=%.0e) and "
                    "color (atol=%.0e rtol=%.0e) ...\n",
            (double)ATOL_DENSITY, (double)RTOL_DENSITY,
            (double)ATOL_COLOR,   (double)RTOL_COLOR);
    compare_into(gold_density, got_density, N,
                 ATOL_DENSITY, RTOL_DENSITY, &s_d);
    compare_into(gold_color,   got_color,   N * 3,
                 ATOL_COLOR,   RTOL_COLOR,   &s_c);
    int fd_fail = report("density", gold_density, N,
                         ATOL_DENSITY, RTOL_DENSITY, &s_d);
    int fc_fail = report("color  ", gold_color,   N * 3,
                         ATOL_COLOR, RTOL_COLOR, &s_c);

    free(nm_work); free(ts_work); free(features); free(positions);
    free(got_color); free(got_density);
    safetensors_close(sf);

    if (fd_fail == 0 && fc_fail == 0) {
        printf("\nPASS  density+color parity (N=%zu density, N=%zu color)\n",
               N, N * 3);
        return 0;
    }
    fprintf(stderr,
            "\nFAIL  parity: density=%d color=%d failures\n",
            fd_fail, fc_fail);
    return 1;

fail2:
    free(nm_work); free(ts_work); free(features); free(positions);
    free(got_color); free(got_density);
fail:
    safetensors_close(sf);
    return 1;
}
